### ISSUE TITLE
errors in concept linking (needs to be corrected)

### ISSUE THREAD

**Issue by LinguList** [clics/clics2#16]
[errors.txt](https://github.com/lingpy/clics-data/files/1747783/errors.txt)

Most errors are due to NorthEuralex (too lax linkings). Many also in the list by Nurse (long list), the rest is marginal. All should be corrected to make sure that we have a good representation of the data in CLICS.

**Comment by xrotwang** [comment]
How do we stand on this issue? Should we close here and transfer remaining problems to issues in the respective dataset repos?

**Comment by LinguList** [comment]
Yes! In fact, I think I fixed most on my side, at least as far as I remember.
