### ISSUE TITLE
[release of 1.0] Check for FALL maps to concepticon in all datasets

### ISSUE THREAD

**Issue by LinguList** [clics/clics2#27]
Some datasets have a strange bias linking "fall" in the meaning of "autumn" to "fall = descend"! I suspect TLS, Bowern's data, and maybe some other datasets. Sun1991 as well. But it is very strange... So please all data maintainers, quickly check whether this is normal. Check for the auto-produced subgraph for "summer" for referenceof this error.

**Comment by xrotwang** [comment]
Here are all datasets that have AUTUMN at all:
```
$ grep 1276 */cldf/parameters.csv
cals/cldf/parameters.csv:autumn,autumn,1276,AUTUMN
ids/cldf/parameters.csv:14-770,autumn,1276,AUTUMN
northeuralex/cldf/parameters.csv:HerbstN,Herbst::N,1276,
suntb/cldf/parameters.csv:autumn,autumn,1276,AUTUMN
tls/cldf/parameters.csv:fall,fall,1276,AUTUMN,
wold/cldf/parameters.csv:14-77,the autumn/fall,1276,AUTUMN
```

**Comment by LinguList** [comment]
It looks like it's only TLS, as this should be linked to "fall" = descend (or not, @tresoldi ?). Strangely, I find this only in the app, not in the SQLITE, so the creation of the app still seems to be extremely buggy...

**Comment by LinguList** [comment]
Or I was just not paying attention to another step for the standalone app creation ?

**Comment by xrotwang** [comment]
No, it seems already db loading is buggy:
```
sqlite> select distinct f.dataset_ID from formtable as f, parametertable as p where f.parameter_id = p.id and p.concepticon_id = '1276';
lexibank-bowernpny
lexibank-ids
lexibank-northeuralex
lexibank-satterthwaitetb
lexibank-suntb
lexibank-tls
lexibank-tryonsolomon
lexibank-wold
```

**Comment by xrotwang** [comment]
datasets are loaded with forms for AUTUMN, even though the datasets doesn't have AUTUMN in its `parameters.csv`.

**Comment by xrotwang** [comment]
Hm. that's a bit scary. I'm investigating.

**Comment by xrotwang** [comment]
Ok, Not as scary, hopefully:
```
sqlite> select distinct f.dataset_ID from formtable as f, parametertable as p where f.parameter_id = p.id and f.dataset_id = p.dataset_id and p.concepticon_id = '1276';
lexibank-ids
lexibank-northeuralex
lexibank-suntb
lexibank-tls
lexibank-wold
```
So maybe this is just a buggy db query in pyclics, which doesn't take into account that we always have composite primary keys (`id`, `dataset_id`) in the db. (See @SimonGreenhill - it's not easy)

Will investigate after lunch.

**Comment by LinguList** [comment]
Okay, relieved this is NOT the data! I was getting scared...

**Comment by xrotwang** [comment]
The first paper retraction in LT! Yeah! :)

Johann-Mattis List <notifications@github.com> schrieb am Do., 28. Juni
2018, 12:57:

**Comment by xrotwang** [comment]
All good again: https://github.com/clics/clics2/commit/6c41d5d3573a706039c2edca27900982e9f39402#diff-f98b9409af68c1f168b8712d59d026d8

**Comment by xrotwang** [comment]
![screenshot from 2018-06-28 15-59-47](https://user-images.githubusercontent.com/870184/42038885-5492064e-7aec-11e8-99a7-42f435b56b54.png)
