### ISSUE TITLE
Add glottocode and bibkey to exported (downloadable data)

### ISSUE THREAD

**Issue by tresoldi** [clics/clics2#30]
I was informally approached by people from the Mint group, they are very interested in the data but asked if the glottocodes could be added to the downloadable data (especially that from the concepts' page themselves, such as http://clics.clld.org/parameters/1867#2/25.9/0.9 ).

Thinking about what people were asking @LinguList today, it would be a good idea to also add the bibkey for each entry.

**Comment by LinguList** [comment]
I'd say, they should run the very simple `pyclics` api and follow the readme, using sqlite to extract the data? I mean, if they have specific requests, we could even publish this with [our calc blog](https://calc.hypotheses.org), i.e., a howto on how to extract all languages with glottocodes that express a certain concept?

**Comment by LinguList** [comment]
But this would be easier than the download option.

**Comment by xrotwang** [comment]
Yes! I spent several years trying to implement the right amount and convenience of download options to the clld apps - and failed. These days, I think, making the "raw" data discoverable and accessible is all I'm willing to do :)

**Comment by xrotwang** [comment]
And btw.: This http://clics.clld.org/parameters/1867.geojson has glottocode :)

**Comment by LinguList** [comment]
So, @tresoldi, maybe we tell the minties interested in this, they should come by and we show them how it's done in pure code...

**Comment by tresoldi** [comment]
Ok, I'll sum this up for them and we should probably have a post on how to do that in our todo list. It would go beyond the simple glottocode information, and more in line with the "how to use these new tools".

Closing the issue.
