### ISSUE TITLE
pin all dependencies?

### ISSUE THREAD

**Issue by xrotwang** [clics/clics2#40]
To allow for maximal replicabiity, we might want to pin **all** dependencies - although that means less good usability?

Actually, we might also just add pinned dependencies to `datasets.txt`.

**Comment by LinguList** [comment]
Yes, for the emotion paper, I already did a pip-freeze, if remember properly. As some packages also keep changing, we'd better really list all with version etc.

**Comment by xrotwang** [comment]
@chrzyki you just had a fresh install, i.e. one with the latest versions, right? Maybe you could add your `pip freeze` results as `requirements.txt` to the repos?

**Comment by chrzyki** [comment]
Sure! Should this be without or with the datasets in `requirements.txt`?

**Comment by xrotwang** [comment]
I'd opt for an additional file, to allow installing software and data separately.
