### ISSUE TITLE
factor out pyclics into its own repos

### ISSUE THREAD

**Issue by xrotwang** [clics/clics2#41]
In the light of issues like #40 it may be better to move `pyclics` into its own repository, making it more transparent that this is simply a library to be used with lexibank datasets to create colexification networks.

The `clics2` repository would then be the one holding the CLICS dataset, i.e. a particular version of `pyclics` applied to a particular set of datasets.

Or would this be too much re-arranging?

**Comment by xrotwang** [comment]
Yes. Possibly we could even re-release CLICS 2 as a dataset.
We should stick to "only-the-network", then, I guess - to not blow up dataset size unnecessarily.

**Comment by chrzyki** [comment]
That is done, correct? https://github.com/clics/pyclics

**Comment by xrotwang** [comment]
yep, done.
