### ISSUE TITLE
Should we aim for pylexibank 1.0 for this paper?

### ISSUE THREAD

**Issue by xrotwang** [clics/clics2#43]
I think cutting a 1.0 release of [pylexibank](https://github.com/lexibank/pylexibank/) would be good. It nothing else it will document our commitment to maintain this data processing pipeline (in particular since we decided that breaking changes would be acceptable for pylexibank < 1.0).

**Comment by LinguList** [comment]
Yes, and the paper is not going to appear that soon, so having this release, we can still think of some kind of lexibank paper to be written this year, without interfering, and if it does NOT work, this can serve as some reference for lexibank.

**Comment by chrzyki** [comment]
Done! https://github.com/lexibank/pylexibank/releases/tag/v1.1.1
