### ISSUE TITLE
Clics tries to write non-ASCII to a GML file

### ISSUE THREAD

**Issue by Anaphory** [clics/clics2#45]
Using `pyclics` on a windows computer, I got the characteristic encoding error that python throws when trying to pump useful characters into windows text files or onto the console.
The culprit sits here:
https://github.com/clics/clics2/blob/97b3121bc2f94c7f417184dc1ffdb8b276a809f8/src/pyclics/models.py#L103-L104
I first tried to force `fp` to have UTF-8 encoding, but closer investigation upon trying to draw the graph showed that `networkx`'s GML reader accepts only ASCII input – why are we unescaping the non-ascii characters in there in the first place, instead of plain using `nx.write_gml(graph, self.fname)`?

**Comment by LinguList** [comment]
Because we want to read the graph in unicode in cytoscape, and cytoscape accepts gml with unicode. We want to look at real word forms when looking at clics data, this is why we write it in this form in GML. The standard is a bit problematic, but was during creation of clics1 useful for inspection, and by then GML problems did not persist.

**Comment by Anaphory** [comment]
If cytoscape could unescape HTML character references, the solution would be to just let `generate_gml` generate those for the IPA symbols, so I assume cytoscape does not have that decoding step?
(For ISO 8859-1, the encoding is actually in the [GML standard](https://www.fim.uni-passau.de/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf), so that would be a bug in cytoscape; on the other hand, the GML standard is way old, so it's forgivable and clean UTF-8 is actually a much better solution nowadays.)

I will just install cytoscape, it's probably the nicer solution anyway.

**Comment by Anaphory** [comment]
I have marked this issue as “won't fix” for now, let's close it and re-open it if ever cytoscape's behaviour changes to permit `&name;`.
