### ISSUE TITLE
More reproducibility issues

### ISSUE THREAD

**Issue by chrzyki** [clics/clics2#47]
With the 'correct' `clics.sqlite` for CLICS2:

```
  ID A  Concept A                     ID B  Concept B                   Families    Languages    Words
------  --------------------------  ------  ------------------------  ----------  -----------  -------
  1313  MOON                          1370  MONTH                             56          289      294
   906  TREE                          1803  WOOD                              55          211      310
  1258  FINGERNAIL                      72  CLAW                              50          209      216
  2266  SON-IN-LAW (OF WOMAN)         2267  SON-IN-LAW (OF MAN)               49          262      285
  2264  DAUGHTER-IN-LAW (OF WOMAN)    2265  DAUGHTER-IN-LAW (OF MAN)          47          235      262
  1608  LISTEN                        1408  HEAR                              47          102      105
   763  SKIN                           629  LEATHER                           46          233      255
   634  MEAT                          2259  FLESH                             46          222      232
  1307  LANGUAGE                      1599  WORD                              45           94       98
  1228  EARTH (SOIL)                   626  LAND                              43          158      181
```

That is correct ✓.

However, I get a different number of edges for the `infomap graph-stats`:

CLICS2:

```
clics -t 3 -g infomap -f families graph-stats   
-----------  ----
nodes        1534
edges        2638
components     96
communities   248
-----------  ----
```

My attempt:

```
clics -t 3 -g infomap -f families graph-stats  
-----------  ----
nodes        1534
edges        2635
components     96
communities   248
-----------  ----
```

I'm not yet sure what the reason for this is and whether it should be any cause for concern.

**Comment by xrotwang** [comment]
Hah, probably hard to debug, but would be really interesting. I'm in the process of recreating clics2 sqlite, too, right now. What does `pip freeze` say in your virtualenv?

**Comment by chrzyki** [comment]
https://gist.github.com/chrzyki/13e11e8471791e6bd151b153ae294596

Just noticed: I installed `pyclics` from the clics2 repository - that might have got something to do with it?

**Comment by xrotwang** [comment]
Nope. That was the procedure then.

Christoph Rzymski <notifications@github.com> schrieb am Mi., 22. Mai 2019,
09:50:

**Comment by xrotwang** [comment]
Hm, funny enough I'm getting
```bash
$ clics -t 3 -g infomap -f families graph-stats   -----------  ----
nodes        1534
edges        2634
components     96
communities   248
-----------  ----
```

**Comment by xrotwang** [comment]
As a first step towards debugging, I inserted a
```python
print(len(edges), len(ignore_edges))
```
here https://github.com/clics/clics2/blob/97b3121bc2f94c7f417184dc1ffdb8b276a809f8/src/pyclics/commands.py#L190
to see whether we are removing different numbers of edges, or adding differently. My numbers are
```
50051  46467
```

**Comment by chrzyki** [comment]
Check!

```
50051 46467
```

**Comment by LinguList** [comment]
Hi, important is that infomap is based on random walks, so different numbers of edges can happen. You need to seed the random function to caputre this, but I'm not sure if igraph allows for this... So I'd say: use nx.connected_components to check for same size, a sthis is the simplest cluster algorithm.

**Comment by xrotwang** [comment]
Ah. Ok, I was chasing down the wrong path! So the actual colexification network is created reproducibly, but the clustering isn't - in the absence of a fixed seed. So, (almost) nothing to see here, move on :)
Except, maybe, we want to find a seed that gives us the number of edges reported in the README :)

**Comment by chrzyki** [comment]
My bad, sorry, wasn't aware of the random walks for the clustering!

**Comment by xrotwang** [comment]
I just added a `--seed` option to the CLI, and
```python
import random
random.seed(args.seed)
```
at the top of the `communities` command. Here's what I get for seed 1 to 4:
```
(clics2) forkel@shh.mpg.de@dlt4803010l:~/venvs/clics2/clics2$ clics -t 3 -s 1 -f families communities
INFO    loaded graph
INFO    starting infomap                                                                                      
INFO    converted graph...
INFO    finished infomap
INFO    computed cluster names
(clics2) forkel@shh.mpg.de@dlt4803010l:~/venvs/clics2/clics2$ clics -t 3 -g infomap -f families graph-stats   -----------  ----
nodes        1534
edges        2630
components     95
communities   247
-----------  ----
(clics2) forkel@shh.mpg.de@dlt4803010l:~/venvs/clics2/clics2$ clics -t 3 -s 2 -f families communitiesINFO    loaded graph
INFO    starting infomap                                                                                      
INFO    converted graph...
INFO    finished infomap
INFO    computed cluster names
(clics2) forkel@shh.mpg.de@dlt4803010l:~/venvs/clics2/clics2$ clics -t 3 -g infomap -f families graph-stats   -----------  ----
nodes        1534
edges        2634
components     96
communities   249
-----------  ----
(clics2) forkel@shh.mpg.de@dlt4803010l:~/venvs/clics2/clics2$ clics -t 3 -s 3 -f families communitiesINFO    loaded graph
INFO    starting infomap                                                                                      
INFO    converted graph...
INFO    finished infomap
INFO    computed cluster names
(clics2) forkel@shh.mpg.de@dlt4803010l:~/venvs/clics2/clics2$ clics -t 3 -g infomap -f families graph-stats   -----------  ----
nodes        1534
edges        2645
components     95
communities   249
-----------  ----
(clics2) forkel@shh.mpg.de@dlt4803010l:~/venvs/clics2/clics2$ clics -t 3 -s 4 -f families communitiesINFO    loaded graph
INFO    starting infomap                                                                                      
INFO    converted graph...
INFO    finished infomap
INFO    computed cluster names
(clics2) forkel@shh.mpg.de@dlt4803010l:~/venvs/clics2/clics2$ clics -t 3 -g infomap -f families graph-stats   -----------  ----
nodes        1534
edges        2637
components     96
communities   247
-----------  ----
```

**Comment by xrotwang** [comment]
So I'd say this is rather a documentation issue, and we may think about adding this seed option into `pyclics` now.

**Comment by xrotwang** [comment]
Hm. Turns out we already had
```python
random.seed(123456)
numpy.random.seed(123456)
```
in `src/pyclics/__main__.py`. So then the question is where does `infomap` get its randomness from?

**Comment by xrotwang** [comment]
Stackoverflow seems to think what we do should be sufficient: https://stackoverflow.com/a/25726079

**Comment by xrotwang** [comment]
Ok, just ran a couple of tests: Running the `community_infomap` method multiple times immediately after setting the seed gives indeed identical clusters. But running the complete `communities` command multiple times - with seed set again immediately before calling `community_infomap` - does not! So I guess, something goes wrong in `networkx2igraph` - maybe we must iterate over the graph nodes explicitly sorting them?

**Comment by xrotwang** [comment]
Ok, confirmed: The order in which vertices are added to `igraph.Graph` in `pyclics.util.networkx2igraph` varies across command calls.

**Comment by chrzyki** [comment]
That's a good find! I was dumbfounded by this ...
