### ISSUE TITLE
Add a cookbook to illustrate how to run a colexification analysis with a small set of data.

### ISSUE THREAD

**Issue by LinguList** [clics/clics2#5]
This is already almost prepared, but it should be adjusted with the new api, and will need some further info on lexibank, etc.

**Comment by xrotwang** [comment]
The [README](https://github.com/clics/clics2/blob/master/README.md) should now cover most of this. What's lacking may be a suitable small lexibank dataset for this.

**Comment by LinguList** [comment]
Yes, I was thinking about taking the old CLICS database, as I might want to shut down the PhP, and replace it with the standalone app. This would mean, that I'd release the old clics data as a bunch (with limited sources, such as IDS, WOLD) to lexibank, as it's already concepticon-mapped, and we could ask people to start from there?

**Comment by LinguList** [comment]
so, sorry, I was talking about CLICS 1.0 ;)

**Comment by xrotwang** [comment]
That's a good idea! You could package it according to the lexibank scheme, but put it in clics/clics1-data or similar.

**Comment by LinguList** [comment]
see [here](https://github.com/clics/clics1), cldf is already produced.

**Comment by xrotwang** [comment]
That was Quick! Will start the cookbook later (today?).

Johann-Mattis List <notifications@github.com> schrieb am Do., 19. Juli
2018, 17:38:

**Comment by LinguList** [comment]
There's one caveat with the current version, I wanted to ask: I pushed the datasets to zenodo earlier [here](https://zenodo.org/record/1194088). Now, I used a custom script (the one we use in the supplementary material, to make the coverage studies) to convert this into a lingpy-style wordlist (since this is easiest for me to handle in this way). Is it okay, to have the clics data raw only in form of that wordlist, or should I integrate that script, maybe even downloading from zenodo, to make things even more correctly tracable? I am considering pushing this clics repository clics/clics1 to zenodo as an update of the one mentioned above. I'd then just add the clics community to it, as well as the lexibank community, and we would not have too many different datasets on zenodo.

**Comment by LinguList** [comment]
Any way: lexibank / clics run so smoothly now, that, if I had not had an appointment at 18:00 today, I'd probably tested out loading this as a single package into clics right away...

**Comment by LinguList** [comment]
runs like a charm. I just made another venv, loaded the new clics, and all goes extremely well. Size of data is ~ 300 MB for clics1, so this is also manageable. I'll upload this now to http://calc.digling.org/clics1/ or similar.

**Comment by LinguList** [comment]
The only problem is that I overwrote my previous clics analyses, but with your plans, @xrotwang, to make an option for an output-dir, this would mean that both the app and the sqlite can be run in different folders or directed there, so no problem at all.

**Comment by LinguList** [comment]
e.g., my scores:

```
$ clics -t 3 -f families -g infomap graph-stats
-----------  ----
nodes        1105
edges        1707
components     83
communities   194
-----------  ----
```

**Comment by xrotwang** [comment]
yep:
```bash
pip install pyclics
pip install -e git+https://github.com/clics/clics1.git#egg=lexibank_clics1
clics load ../concepticon/concepticon-data/ ../glottolog/glottolog
clics -t 3 -f families colexification
clics -t 3 -f families communities
clics -t 3 -f families -g infomap graph-stats
```
gives
```
-----------  ----
nodes        1105
edges        1705
components     83
communities   193
-----------  ----
```

**Comment by xrotwang** [comment]
pretty short cookbook, though :)

**Comment by LinguList** [comment]
I am considering writing a post (or having somebody write a post) for our [calc blog](https://calc.hypotheses.org) on this. We could do it once the paper is officially out, and then tweet it, etc.

**Comment by LinguList** [comment]
Short question: should I release clics1 with Zenodo then? I don't believe we will change much of it in the future, but it would be good to have a version for it...

**Comment by xrotwang** [comment]
Yes, I guess that makes sense for archiving.

**Comment by LinguList** [comment]
Okay, the DOI is here: https://doi.org/10.5281/zenodo.1194087

And I added it to the lexibank and the clics community (but they don't seem to appear there, maybe have to wait a bit).
