### ISSUE TITLE
Relative default paths in pyclics

### ISSUE THREAD

**Issue by Anaphory** [clics/clics2#8]
The default paths in [`pyclics.cli`](https://github.com/lingpy/clics-data/blob/110d866f7615a8ce9cdadc13e53799cb0d342669/pyclics/cli.py#L27) are relative to the directory in which `clics` is executed. This sounds useful in no general case.

Is not something like `Path(pyglottolog.__file__).parent.parent` etc. a reasonable default for those paths? Or even `None`, so the “look for your default data path” can be handled by those clld modules themselves?

**Comment by xrotwang** [comment]
Starting with v1.1 `pyclics` is now a regular python package - i.e. no longer does stuff like writing output to the source tree or an assumed repository clone. Instead, all `clics` subcommands accept the `--output=...` option (defaulting to current working directory) and all output is written to this directory.
